### ISSUE TITLE
Please delete or update

### ISSUE THREAD

**Issue by icemagno** [kiselev-dv/osm-cesium-3d-tiles#3]
Please delete or update this project since it not compile anymore because OSM2world.

**Comment by icemagno** [comment]
Several errors ...

```
# ./osm2world.sh -i /opt/data/osm-tiles/{zoom}/{x}/{y}.osm -o /opt/data/obj-tiles/dummy.obj
java.io.FileNotFoundException: /opt/data/osm-tiles/{zoom}/{x}/{y}.osm
        at org.osm2world.core.osm.creation.OSMFileReader.<init>(Unknown Source)
        at org.osm2world.console.Output.output(Unknown Source)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(Unknown Source)
        at org.osm2world.console.OSM2World.main(Unknown Source)
# ./osm2world.sh -i /opt/data/osm-tiles/12/{x}/{y}.osm -o /opt/data/obj-tiles/dummy.obj
java.io.FileNotFoundException: /opt/data/osm-tiles/12/{x}/{y}.osm
        at org.osm2world.core.osm.creation.OSMFileReader.<init>(Unknown Source)
        at org.osm2world.console.Output.output(Unknown Source)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(Unknown Source)
        at org.osm2world.console.OSM2World.main(Unknown Source)
# ./osm2world.sh -i /opt/data/osm-tiles/12/1553/2314.osm -o /opt/data/obj-tiles/dummy.obj
time terrain interpolation: 0:00:00.577
time add constraints: 0:00:00.000
time enforce constraints: 0:00:00.000
java.io.IOException: No such file or directory
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at org.osm2world.core.target.obj.ObjWriter.writeObjFile(Unknown Source)
        at org.osm2world.console.Output.output(Unknown Source)
        at org.osm2world.console.OSM2World.executeArgumentsGroup(Unknown Source)
        at org.osm2world.console.OSM2World.main(Unknown Source)
#
```
